# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional


__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "bf288028887a6d6cad81fd949cc8d5dc2ac91e31 *"
__dependency_versions__: Dict[str, Optional[str]] = {
    "boost": "unknown",
    "python": "unknown",
    "base": "gca804b0f43+f0a1800e64",
    "pex_exceptions": "g131b30d954+f6e951a35a",
    "numpy": "None",
    "cpputils": "g4e8ce4af8a+d61c1479ad",
    "fftw": "unknown",
    "eigen": "unknown",
    "ndarray": "unknown",
    "starlink_ast": "unknown",
    "astshim": "g1011452fe8+91250f09a0",
    "boost_math": "unknown",
    "sphgeom": "gd5d1ca8e18+f0a1800e64",
    "geom": "g3f8e1907dc+7442544851",
    "daf_base": "g3a7e09fba3+647ad2b4cc",
    "log4cxx": "unknown",
    "log": "g8479130295+37bc81c514",
    "pex_config": "g4f1969f4e1+b66847d792",
    "minuit2": "unknown",
    "gsl": "unknown",
    "cfitsio": "unknown",
    "afw": "g2c743f43ab+04f223c4f0",
    "meas_base": "g91d91042f5+ca8b3fd1b0",
    "meas_algorithms": "gf28172b03b+14260db065",
    "pybind11": "unknown",
    "sdqa": None,
}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
